version: '3.7'

services:
  php:
    build:
      context: .
    container_name: php-app
    ports:
      - "8080:80"
    volumes:
      - ./Application:/var/www/html
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: mysql:5.7
    container_name: php-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

  dashboard:
    image: nginx:latest
    container_name: vuln-dashboard
    ports:
      - "8081:80"
    volumes:
      - ./vuln-dashboard:/usr/share/nginx/html:ro
      - ./trivy-results:/etc/nginx/trivy-results:ro
      - ./vuln-dashboard/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    networks:
      - app_network

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    networks:
      - app_network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - node-exporter
    networks:
      - app_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - app_network

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    networks:
      - app_network

volumes:
  db_data:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:

networks:
  app_network:
    driver: bridge
